spring.datasource.url=jdbc:postgresql://localhost:5432/smartcollab_db
spring.datasource.username=smartcollab_user
spring.datasource.password=smartcollab_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true